### ISSUE TITLE
Card en blanco al hacer clic en Ver Mas

### ISSUE THREAD

**Issue by dlaurora** [ufedev/MoviesReact#1]
Creo que encontré el problema.

Al cambiar

`setMovies([movies, ...res.results])`

por

`setMovies([...movies, ...res.results]);`

Soluciona el problema.

Esto podría estar relacionado con la forma en que actualizamos el estado con las nuevas películas. creo que el error esta en cómo concatenamos las películas anteriores con las nuevas. En lugar de crear una nueva array con las películas existentes seguidas de las nuevas, estámos anidando, y esto creo que provoca el error de la blank card y la poca fluidez al actualizar

**Comment by ufedev** [comment]
Corregido, Gracias por el pullrequest
